### ISSUE TITLE
regression TemplateNotFound: fb4common/base.html

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/ConferenceCorpus#32]
nightly jenkins build fails:
ERROR: testWebServerHome (tests.testWebServer.TestWebServer)
test the home page of the Webserver
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hd/luxio/var/lib/jenkins/jobs/ConferenceCorpus/workspace/corpus/web/webserver.py", line 49, in home
    return self.homePage()
  File "/hd/luxio/var/lib/jenkins/jobs/ConferenceCorpus/workspace/corpus/web/webserver.py", line 118, in homePage
    html=self.render_template(template, title=title, activeItem=activeItem)
  File "/hd/luxio/var/lib/jenkins/jobs/ConferenceCorpus/workspace/corpus/web/webserver.py", line 107, in render_template
    html=render_template(templateName,title=title,menu=self.getMenu(activeItem),copyright=self.copyRight,**kwArgs)
  File "/hd/luxio/var/lib/jenkins/jobs/ConferenceCorpus/workspace/corpus/web/../../templates/cc/home.html", line 1, in top-level template code
    {% extends 'fb4common/base.html' %}
  File "/home/wf/.local/lib/python3.8/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/home/wf/.local/lib/python3.8/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: fb4common/base.html
```
this is strange since there has been no new fb4 release so it might be the state of the unreleased fb4 causing this
jinja2.exceptions.TemplateNotFound: fb4common/base.html

**Comment by WolfgangFahl** [comment]
does not happen on github CI which  hints for being related with the potential prerelease issue of https://github.com/WolfgangFahl/pyFlaskBootstrap4/issues/29
